module.exports = [
    "Tchestita Koleda",
    "Hyvaa joulua",
    "Joyeux Noël",
    "Glædelig Jul",
    "Froehliche Weihnachten",
    "Kala Christouyenna",
    "Mele Kalikimaka",
    "Gledileg Jol",
    "Kellemes Karacsonyi unnepeket",
    "Shub Naya Baras",
    "Selamat Hari Natal",
    "Kurisumasu omedeto",
    "Idah Saidan Wa Sanah Jadidah",
    "Nollaig Shona Dhuit",
    "Buone Feste Natalizie",
    "Sung Tan Chuk Ha",
    "Linksmu Kaledu",
    "Merry Keshmish",
    "God Jul",
    "Wesolych Swiat Bozego Narodzenia",
    "Feliz Natal",
    "Craciun fericit",
    "Hristos se rodi",
    "Sretan Bozic or Vesele vianoce",
    "La Maunia Le Kilisimasi Ma Le Tausaga Fou",
    "Nollaig chridheil huibh",
    "Sretam Bozic. Vesela Nova Godina",
    "Vesele Vianoce. A stastlivy Novy Rok",
    "Vesele Bozicne. Screcno Novo Leto",
    "Feliz Navidad",
    "Ia orana te Noera",
    "Sawadee Pee Mai",
    "Noeliniz Ve Yeni Yiliniz Kutlu Olsun",
    "Z Rizdvom Khrystovym",
    "Chuc Mung Giang Sinh",
    "Nadolig Llawen",
    "Cestitamo Bozic"
]